#!/usr/bin/env bash
# generate_reads.sh — build the CallForge REAL-reference sim fixture on the cluster.
#
# Resolves planted variants against the REAL GRCh38 FASTA + gene model, then simulates
# per-sample reads with dwgsim — BOTH steps run INSIDE the .sif (need pysam + dwgsim).
# The reviewable plan (simulate_cohort.py) runs on the host.
#
# Reads are simulated from REAL reference sub-sequence at REAL coordinates; nothing is
# faked. Variants are consequence-verified against the real CDS during resolution.
#
# Usage:
#   CALLFORGE_SIF=/path/callforge.sif \
#   ./generate_reads.sh <outdir> <GRCh38_noalt.clean.fa> <ensembl.gtf[.gz]> [engine] [known.vcf.gz]
#     <outdir>     writable fixture dir (scratch/project — NOT the read-only install)
#     <fasta>      real GRCh38 no-alt FASTA (.fai beside it)
#     <gtf>        gene-model GTF (Ensembl) — authoritative exon/CDS for placement
#     engine       singularity (default) | apptainer
#     known.vcf.gz optional gnomAD/dbSNP (tabixed) -> novelty/collision checks during placement
#
# After this: run the pipeline against <outdir>/sim.params.yaml, then check_against_truth.py.
set -euo pipefail

OUTDIR="${1:?usage: generate_reads.sh <outdir> <fasta> <gtf> [engine] [known.vcf.gz]}"
FASTA="${2:?need the real GRCh38 no-alt FASTA}"
GTF="${3:?need the gene-model GTF}"
ENGINE="${4:-singularity}"
KNOWN="${5:-}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "${HERE}/../.." && pwd)"
mkdir -p "$OUTDIR"; OUTDIR="$(cd "$OUTDIR" && pwd)"

case "$ENGINE" in singularity|apptainer) ;; *)
  echo "[generate_reads] ERROR: engine must be singularity|apptainer (got '$ENGINE')" >&2; exit 2 ;;
esac
[[ -s "$FASTA" ]] || { echo "[generate_reads] ERROR: FASTA not found: $FASTA" >&2; exit 2; }
[[ -s "$GTF"   ]] || { echo "[generate_reads] ERROR: GTF not found: $GTF" >&2; exit 2; }

# 1) reviewable plan + sample sheet (host, stdlib)
python3 "${HERE}/simulate_cohort.py" --outdir "${OUTDIR}" --fixture-dir "${OUTDIR}"

run_in_sif() {
  if [[ -z "${CALLFORGE_SIF:-}" ]]; then
    echo "[generate_reads] CALLFORGE_SIF unset; trying host python (needs pysam + dwgsim on PATH)" >&2
    "$@"
  else
    local binds="--bind ${REPO} --bind ${OUTDIR} --bind $(dirname "$FASTA") --bind $(dirname "$GTF")"
    [[ -n "$KNOWN" ]] && binds="$binds --bind $(dirname "$KNOWN")"
    $ENGINE exec $binds "${CALLFORGE_SIF}" "$@"
  fi
}

# 2) resolve planted variants at real coords (consequence-verified) -> truth manifest + BED
known_arg=(); [[ -n "$KNOWN" ]] && known_arg=(--known "$KNOWN")
run_in_sif python3 "${HERE}/resolve_variants.py" \
  --fasta "$FASTA" --gtf "$GTF" --outdir "$OUTDIR" "${known_arg[@]}"

# 3) simulate per-sample reads from the real reference (dwgsim)
run_in_sif python3 "${HERE}/simulate_reads.py" \
  --fasta "$FASTA" --manifest "${OUTDIR}/truth_manifest.json" --outdir "$OUTDIR"

# 4) turnkey params for the pipeline run (spine needs ONLY the genome; annotation/burden
#    need the staged DBs — fill those in as they come online; see README dependency map).
cat > "${OUTDIR}/sim.params.yaml" <<YAML
# CallForge real-reference simulation params (generated by generate_reads.sh).
# SPINE (align->QC->call->cnv->str) needs ONLY the genome below + the STR catalog.
# Annotation/burden/cohortqc need the staged real DBs (fill in, then re-run those stages).
genome_build:    ${GENOME_BUILD:-GRCh38}
genome_fasta:    ${FASTA}
gtf:             ${GTF}
target_bed:      ${OUTDIR}/ref/targets.bed
gene_metadata:   ${OUTDIR}/ref/gene_metadata.tsv
str_catalog:     ${OUTDIR}/ref/str_catalog.json
input:           ${OUTDIR}/samplesheet.csv
outdir:          ${OUTDIR}/results
paralog_genes:   ''
cnv_caller:      cnvkit
burden_engine:   collapse        # tiny cohort -> collapse/SKAT; regenie needs more samples
burden_af_max:   0.01
# ---- staged real DBs (annotation/burden/cohortqc) — fill from fetch_annotation_refs.sh ----
# vep_cache:       /refs/vep
# vep_mode:        cache
# phylop_bw:       /refs/phyloP100way.bw
# gnomad_vcf:      /refs/gnomad.afr.sites.vcf.gz
# gnomad_af_field: AF_afr
# dbsnp_vcf:       /refs/dbsnp.vcf.gz
# clinvar_vcf:     /refs/clinvar.vcf.gz
# somalier_sites:  /refs/somalier.sites.GRCh38.vcf.gz
# known_sites:     /refs/dbsnp.vcf.gz,/refs/Mills.indels.vcf.gz
container_image: ${CALLFORGE_SIF:-/PATH/TO/callforge.sif}
slurm_partition: FILL_ME
bind_paths:      /hpc
YAML

echo "[generate_reads] fixture ready: ${OUTDIR}"
echo "  spine run (genome only):  callforge-run -params-file ${OUTDIR}/sim.params.yaml -profile hpc_slurm,${ENGINE}"
echo "  spine check:              python3 ${HERE}/check_against_truth.py --manifest ${OUTDIR}/truth_manifest.json --results ${OUTDIR}/results --through 9"
