#!/usr/bin/env python3
"""simulate_reads.py — simulate per-sample reads FROM the real GRCh38 reference (cluster).

Consumes the RESOLVED truth_manifest.json + the real FASTA and produces, per sample,
paired-end FASTQs that carry the planted variants at their REAL coordinates:

  * heterozygous variants: two haplotypes per region (hapA=ref, hapB=variant), each
    simulated at half depth -> ~0.5 allele balance.
  * CNV: the gene's target depth is modulated per carrier (DEL ~0.45x, DUP ~1.8x).
  * STR: HTT carriers get an EXPANDED (CAG)n tract spliced into hapB at the real locus.
  * sex: real X/Y off-target windows are simulated at ploidy-scaled depth (F: 2x X, 0 Y;
    M: 1x X, 1x Y) so somalier infers sex from REAL reference coverage.

Reads are generated by **dwgsim** (a real Illumina-error-model simulator) with germline
mutation OFF (`-r 0`) — the only variants present are the ones WE bake into hapB, so there
are no spurious calls. Reads are simulated from real sub-sequence windows; when the
pipeline aligns them to full GRCh38 they land at their true coordinates.

Requires dwgsim + pysam in the .sif. Run inside the container (generate_reads.sh does).
"""
import argparse
import glob
import gzip
import json
import os
import shutil
import subprocess
import sys
import zlib

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cohort_design as D

COMP = str.maketrans("ACGTNacgtn", "TGCANtgcan")
READLEN = 150
FRAG, FRAG_SD = 350, 50


def dseed(*parts):
    return (zlib.crc32("|".join(str(p) for p in parts).encode()) ^ D.SEED) & 0x7FFFFFFF


def apply_edits(window, w_start0, edits):
    """Apply [(pos1,ref,alt)] to a window (str). w_start0 = window's 0-based genomic start.
    Returns edited string; edits applied right-to-left so indels don't shift earlier ones."""
    seq = window
    for pos1, ref, alt in sorted(edits, key=lambda e: -e[0]):
        li = pos1 - 1 - w_start0
        if li < 0 or li + len(ref) > len(seq):
            continue
        if seq[li:li + len(ref)].upper() != ref.upper():
            sys.stderr.write(f"[simulate_reads] WARN: ref mismatch at {pos1} "
                             f"(window has {seq[li:li+len(ref)]}, expected {ref}) — skipped\n")
            continue
        seq = seq[:li] + alt + seq[li + len(ref):]
    return seq


def dwgsim_region(seq, cov, seed, workdir, tag, dwgsim):
    """Simulate reads from a one-contig FASTA of `seq` at coverage `cov`. Returns (r1,r2)."""
    if cov <= 0 or len(seq) < FRAG:
        return None, None
    fa = os.path.join(workdir, f"{tag}.fa")
    with open(fa, "w") as fh:
        fh.write(f">{tag}\n")
        for i in range(0, len(seq), 60):
            fh.write(seq[i:i + 60] + "\n")
    pref = os.path.join(workdir, tag)
    cmd = [dwgsim, "-C", f"{cov:.2f}", "-1", str(READLEN), "-2", str(READLEN),
           "-d", str(FRAG), "-s", str(FRAG_SD), "-r", "0", "-R", "0", "-y", "0",
           "-z", str(seed), "-e", "0.001-0.005", "-E", "0.001-0.005", fa, pref]
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    r1 = (glob.glob(pref + "*read1*.fastq*") or [None])[0]
    r2 = (glob.glob(pref + "*read2*.fastq*") or [None])[0]
    return r1, r2


def open_maybe_gz(path):
    return gzip.open(path, "rt") if path.endswith(".gz") else open(path)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--fasta", required=True)
    ap.add_argument("--manifest", required=True, help="RESOLVED truth_manifest.json")
    ap.add_argument("--outdir", required=True)
    ap.add_argument("--depth", type=int, default=40, help="target het depth (per-hap = depth/2)")
    ap.add_argument("--samples", default=None, help="comma list to limit (default: all)")
    a = ap.parse_args()

    dwgsim = shutil.which("dwgsim")
    if not dwgsim:
        sys.exit("[simulate_reads] ERROR: dwgsim not on PATH (rebuild the .sif after adding "
                 "dwgsim to env/callforge.yml).")
    try:
        import pysam
    except ImportError:
        sys.exit("[simulate_reads] ERROR: pysam required (run inside the .sif).")

    man = json.load(open(a.manifest))
    fa = pysam.FastaFile(a.fasta)
    fqdir = os.path.join(a.outdir, "fastq")
    work = os.path.join(a.outdir, ".readwork")
    os.makedirs(fqdir, exist_ok=True)
    os.makedirs(work, exist_ok=True)

    # parse the resolved target BED into intervals (gene, class)
    bed = []
    with open(man["target_bed"]) as fh:
        for line in fh:
            f = line.split("\t")
            if len(f) >= 4:
                gene, _, klass = f[3].partition("|")
                bed.append({"chrom": f[0], "start": int(f[1]), "end": int(f[2]),
                            "gene": gene, "klass": klass.strip()})

    # planted edits by sample
    def edits_for(sample):
        out = {}   # chrom -> [(pos,ref,alt)]
        for t in man["coding_variants"] + man["promoter_variants"]:
            if sample in t["carriers"]:
                out.setdefault(t["contig"], []).append((t["pos"], t["ref"], t["alt"]))
        return out

    cnv_by_gene = {}
    for e in man["cnv_events"]:
        for c in e["carriers"]:
            cnv_by_gene[(c, e["gene"])] = e["fold"]
    str_info = man["str"]
    str_carriers = set(str_info["carriers"])
    sample_filter = set(a.samples.split(",")) if a.samples else None

    for s in man["samples"]:
        sid = s["sample_id"]
        if sample_filter and sid not in sample_filter:
            continue
        sex = s["sex"]
        edits = edits_for(sid)
        r1_out = os.path.join(fqdir, f"{sid}_R1.fastq")
        r2_out = os.path.join(fqdir, f"{sid}_R2.fastq")
        open(r1_out, "w").close()
        open(r2_out, "w").close()

        def emit(seq, cov, tag):
            r1, r2 = dwgsim_region(seq, cov, dseed(sid, tag), work, f"{sid}_{tag}", dwgsim)
            for src, dst in ((r1, r1_out), (r2, r2_out)):
                if src:
                    with open_maybe_gz(src) as ih, open(dst, "a") as oh:
                        shutil.copyfileobj(ih, oh)
            for f in glob.glob(os.path.join(work, f"{sid}_{tag}*")):
                os.remove(f)

        # ---- target intervals: two haplotypes (het), CNV depth modulation, STR expansion
        for i, iv in enumerate(bed):
            seq = fa.fetch(iv["chrom"], iv["start"], iv["end"]).upper()
            if not seq or set(seq) <= {"N"}:
                continue
            fold = cnv_by_gene.get((sid, iv["gene"]), 1.0)
            hap_cov = a.depth * fold / 2.0
            iv_edits = [(p, r, al) for (p, r, al) in edits.get(iv["chrom"], [])
                        if iv["start"] <= p - 1 < iv["end"]]
            # hapA = reference
            emit(seq, hap_cov, f"{i}_A")
            # hapB = variant haplotype (SNV/indel; STR expansion for HTT carriers)
            hapB = apply_edits(seq, iv["start"], iv_edits)
            if iv["klass"] == "str" and sid in str_carriers:
                rs, re_ = (int(x) for x in str_info["repeat_region"].split(":")[1].split("-"))
                li = rs - 1 - iv["start"]
                tract_len = re_ - rs + 1
                if 0 <= li and li + tract_len <= len(hapB):
                    hapB = hapB[:li] + str_info["motif"] * str_info["expanded_units"] + hapB[li + tract_len:]
            emit(hapB, hap_cov, f"{i}_B")

        # ---- sex off-target (real X/Y), ploidy-scaled depth
        xr = man["sex_regions"]["X"]
        xseq = fa.fetch(xr["chrom"], xr["window"][0], xr["window"][1]).upper()
        emit(xseq, a.depth if sex == "F" else a.depth / 2.0, "sexX")
        if sex == "M":
            yr = man["sex_regions"]["Y"]
            yseq = fa.fetch(yr["chrom"], yr["window"][0], yr["window"][1]).upper()
            emit(yseq, a.depth / 2.0, "sexY")

        for out in (r1_out, r2_out):
            subprocess.run(["bgzip", "-f", out], check=True)
        print(f"[simulate_reads] {sid} ({sex}) done -> {fqdir}/{sid}_R{{1,2}}.fastq.gz")

    shutil.rmtree(work, ignore_errors=True)
    print(f"[simulate_reads] all samples done. Reads carry planted variants at REAL coords.")


if __name__ == "__main__":
    main()
